# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='images')),
                ('cost', models.FloatField()),
                ('specifictions', models.PositiveSmallIntegerField(choices=[(1, 'Structure'), (2, 'Kitchens'), (3, 'Main Bathrooms'), (4, 'Balconies'), (5, 'Walls'), (6, 'Floors'), (7, 'Cielings'), (8, 'Cupboards'), (9, 'Heating/Ventilation'), (10, 'Lightining/Electrical'), (11, 'Lifts'), (12, 'Joinery')], default=1)),
                ('location', models.CharField(max_length=50)),
                ('property_type', models.PositiveIntegerField(choices=[(1, 'Apartment/Flat'), (2, 'Independent House'), (3, 'Hostel'), (4, 'Paying Guest'), (5, 'Guest House'), (6, 'Holiday Home'), (7, 'Farm House'), (8, 'Residential Plot/Land'), (9, 'Shop'), (10, 'Showroom'), (11, 'Office Space'), (12, 'Shopping Mall Space'), (13, 'Hotel/Resort'), (14, 'Industrial Building'), (15, 'Business Center')], default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
